import java.util.ArrayList;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static ArrayList<String> reverse(ArrayList<String> stuffToReverse) {
        ArrayList<String> ans = new ArrayList<>();
        for(int i = stuffToReverse.size() - 1; i >= 0; i--) {
            ans.add(stuffToReverse.get(i));
        }
        return ans;
    }
}
