import com.google.gson.Gson;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Gson gson = new Gson();
        System.out.println(new int[]{1,2,3});
    }
}
