import com.google.gson.Gson;

import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        for (String arg : args) {
            System.out.println(arg);
        }
        Cloud yesterdayStratus = new Cloud(2, 10000, "stratus", false, false);
        Gson gson = new Gson();
        String json = "[{\"name\": \"Frank\", \"age\": 2, \"favoriteCloud\": " + gson.toJson(yesterdayStratus) + "}, {\"name\": \"Fernanda\", \"age\": 6}, {}]";
        System.out.println(json);
        Dolphin[] frank = gson.fromJson(json, Dolphin[].class);
        System.out.println(Arrays.toString(frank));
        System.out.println(yesterdayStratus);
        System.out.println(frank[0].favoriteCloud);
        System.out.println(yesterdayStratus == frank[0].favoriteCloud);
        System.out.println(yesterdayStratus.equals(frank[0].favoriteCloud));
        System.out.println("apple" == "apple");
        System.out.println("a".equals("a"));
    }

    public static void playingWithGson() {
        System.out.println(new App().getGreeting());
        Gson gson = new Gson();
        System.out.println(new int[]{1,2,3});
        Cloud yesterdayStratus = new Cloud(2, 10000, "stratus", false, false);
        System.out.println(yesterdayStratus);
        String jsonOfCloud = gson.toJson(yesterdayStratus);
        System.out.println(jsonOfCloud);
        Cloud cloudFromJson = gson.fromJson(jsonOfCloud, Cloud.class);
        FlyingPillow pillowFromJson = gson.fromJson(jsonOfCloud, FlyingPillow.class);
        System.out.println(pillowFromJson);
    }
}
