/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class BookReaderTest {
    @Test public void testAppHasAGreeting() {
        BookReader classUnderTest = new BookReader();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
