/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testPrintStuff() {
        int[] intArr = new int[]{7,8,12,3};
        //Library.printStuff(intArr);
        ArrayList<Integer> nums = new ArrayList<>();
        nums.add(1);
        nums.add(7);
        Library.printStuff(nums);
        Set<String> people = new HashSet<>();
        people.add("Sooz");
        people.add("Tara");
        Library.printStuff(people);
    }
}
