import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Flower ourRose = new Flower();
        Flower ourRose = new Flower("rose", "red", 8, true, false);
//        ourRose.type = "rose";
        System.out.println(ourRose.type);
        System.out.println(ourRose.petals);
        Flower ourTulip = new Flower("tulip", "purple", 5, true, true);
        System.out.println(ourTulip.color);
        Flower ourSunflower = new Flower("sunflower", "yellow", 0, false, true);
        System.out.println(ourSunflower.blooming);
        ourSunflower.bloom();
        System.out.println(ourSunflower.blooming);

        System.out.println(Arrays.toString(Flower.types));
    }
}
