import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Quote q = null;
        try {
            QuoteGetter getter = new WebQuoteGetter();
            q = getter.getQuote();
        } catch (IOException e) {
            // there was an issue with the internet quote getter
        }
        if (q == null) {
            try {
                QuoteGetter getter = new FilesystemQuoteGetter("bad/resources/quotes.json");
                q = getter.getQuote();
            } catch (IOException eTwo) {
                q = new Quote(
                        "Michelle Ferreirae",
                        "Sometimes, the filesystem does not like you.");
            }
        }
        System.out.println(q);
    }
}
