/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void printStuff(Iterable stuff) {
        for (Object thing : stuff) {
            System.out.println(thing);
        }
    }
}
