import java.util.HashMap;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class BookReader {
    public String getGreeting() {
        return "Hello world.";
    }

    private HashMap<String, Integer> makeFakeHashMap() {
        HashMap<String, Integer> ans =  new HashMap<>();
        ans.put("hello", 2);
        ans.put("world", 1);
        return ans;
    }

    public static void main(String[] args) {
        System.out.println(new BookReader().makeFakeHashMap());
    }
}
